catalog = {
    'abm': "alt_backup_marker",
    'altfile': "another_filename",
    'called': "called",
    'closed': "This file is already closed",
    'crlf': "\r\n",
    'dfid': ".fiddle",
    'dfmt': ".%Y.%m%d.%H%M%S",
    'err': "Error",
    'flake_cmd': "flake8 conftest.py editor tests",
    'frib': "fribble",
    'froo': ".frooble",
    'frst': "First line",
    'last': "Last line",
    'load': "load",
    'lowe': "e",
    'miss': "No filepath specified",
    'new': "This line is not in the original test data",
    'nwfl': "newfile",
    'one': "one",
    'oops': "Oops! I should not have added this line",
    'ovwr': "To overwrite it",
    'save': "save",
    'stst': " test",
    'test': "test",
    'two': "two",
    'uppE': "E",
    'wump': ".wumpus",
    'whsp': "     ",
    'with': "with_whitespace",
    'ymdf': ".%Y%b%d",
    }
