catalog = {
    'abm': "alt_backup_marker",
    'after': "This goes after the last line",
    'altfile': "another_filename",
    'before': "This goes before the first line",
    'bkup': ".backup",
    'called': "called",
    'closed': "This file is already closed",
    'crlf': "\r\n",
    'dfid': ".fiddle",
    'dfmt': ".%Y.%m%d.%H%M%S",
    'drgx': "\.\d{4}\.\d{4}\.\d{6}",
    'err': "Error",
    'flake_cmd': "flake8 conftest.py editor tests",
    'frib': "fribble",
    'froo': ".frooble",
    'frst': "First line",
    'last': "Last line",
    'load': "load",
    'lowa': "a",
    'lowe': "e",
    'middle': "This goes in the middle",
    'miss': "No filepath specified",
    'new': "This line is not in the original test data",
    'nwfl': "newfile",
    'one': "one",
    'oops': "Oops! I should not have added this line",
    'orig_l': ["This is a file containing",
               "several lines of test data",
               "to start us out on the",
               "overwrite test."],
    'ovwr': "To overwrite it",
    'ovwr_l': ["This is the overwriting data",
               "Once the test is done, this",
               "should no longer be present."],
    'save': "save",
    'stst': " test",
    'test': "test",
    'two': "two",
    'uppA': "A",
    'uppE': "E",
    'wump': ".wumpus",
    'whsp': "     ",
    'with': "with_whitespace",
    'ymdf': ".%Y%b%d",
    'ymd_rgx': "^\.\d{4}\w{3}\d{2}$",
    }
